### PR TITLE
Add some useful outputs to debug errors

### PR DESCRIPTION
**Pull request by brayanhenao**

### CODE REVIEW

**Comment by flavorjones** [comment]
@brayanhenao Any reason you wouldn't want to send a PR upstream for changes like this? :pray:

**Comment by flavorjones** [comment]
(Upstream meaning to https://github.com/flavorjones/mini_portile)

**Comment by brayanhenao** [comment]
Hi @flavorjones!

Initially, these changes were intended to detect errors in the cf-buildpacks repositories that use this fork. I would be happy to send a similar PR to the upstream if you want!

It is quite interesting to obtain information about the URL from which the file is downloaded, the parameters, and also if an HTTP error occurs when trying to download it, to know everything about it.

**Comment by flavorjones** [comment]
Yes, please!

**Pull request merged**
